### ISSUE TITLE
Radio wont play at all

### ISSUE THREAD

**Issue by CodingNinja223** [knyar/svitle-radio-mobile#8]
So I'm going thought the code and was able to run the app on my emulator but it's giving me issues like actually playing the radio or showing more info on the other screens its like I have a minified version of the app

**Comment by knyar** [comment]
As mentioned in the README, this app relies on a server side API to discover stream metadata and other dynamic information. URL of that API endpoint is configured in `app/config/env.dev.js` (development version) and `env.prod.js` (production version).

Development version expects API at `http://10.11.12.21:5000`, but you can change it in `env.dev.js`. If you want to run it against our production API, you can simply change `API_URL` in `env.dev.js` to `https://m.svitle.org/v2`.

Used API endpoints are:
- App preferences, contact information, list of stations: https://m.svitle.org/v2/preferences.svitle
- Metadata for a specific station: https://m.svitle.org/v2/status?station=svitle

Source code for the API server is available here: https://github.com/knyar/svitle-api/

If you wanted to run the app without API (with all data hard-coded) you can adjust `app/models/main-store.ts` and make `getPreferences` and `updateStreamInfo` provide static values instead of getting them via HTTP.
